import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../app/layout/header_two'
import Footer from '../app/layout/footer'
import ScrollProvider from '../app/common/scrollProvider'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<>

    <Header />
    <html lang="en">

      <body
        className={`antialiased`}
      >
        <ScrollProvider>
          {children}
        </ScrollProvider>
      </body>

    </html>
    <Footer />
  </>
  );
}
