import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../app/layout/header_two'
import Footer from '../app/layout/footer'
import ScrollProvider from '../app/common/scrollProvider'
import ChatWidget from "./components/chatBot/chatWidget";
import Provider from "./common/provider";
import {DirectionProvider} from '../app/components/ContextProvider'
export const metadata = {
  title: "Leap Events",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/favico.ico", // <--- Updated file name here
        sizes: "96x96",
        type: "image/png",
      },
    ],
    shortcut: "/favico.ico",
    apple: "/favico.ico",
  },
};

export default function RootLayout({ children }) {
  return (<>


    <html lang="en">
      <head>
<script src="https://elfsightcdn.com/platform.js" async></script>

        <script src="https://elfsightcdn.com/platform.js" strategy="lazyOnload" />
        {/* <script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="lazyOnload"
        /> */}
        {/* <script id="google-translate-init" strategy="lazyOnload">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement({
                pageLanguage: 'en',
                includedLanguages: 'ar'
              }, 'google_translate_element');
            }
          `}
        </script> */}
        </head>
      <body
        className={`antialiased`}
      >
            <DirectionProvider>
        <Provider>
        <ScrollProvider>
          <Header />
              {children}
           <Footer />

        
          <ChatWidget />
        </ScrollProvider>
        </Provider>
           </DirectionProvider>
      </body>

    </html>
  </>
  );
}
