import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../app/layout/header'
import Footer from '../app/layout/footer'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<>

    <Header />
    <html lang="en">

      <body
        className={`antialiased`}
      >

        {children}

      </body>

    </html>
    <Footer />
  </>
  );
}
